version: '3.8'

services:
  redis:
    image: redis:7-alpine # Use a specific Redis version
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net: 